{% set version = "0.4.1" %}

package:
  name: flexx
  version: {{ version }}

source:
  fn: flexx-{{ version }}.zip
  url: https://github.com/zoofIO/flexx/archive/v{{ version }}.tar.gz

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  number: 0

requirements:
  build:
    - python
    - setuptools
    - tornado
  run:
    - python
    - tornado

test:
  imports:
    - flexx.ui
    - flexx.app
    - flexx.event
    - flexx.pyscript
    - flexx.webruntime
    - flexx.util

about:
  home: http://github.com/zoofIO/flexx
  doc_url: http://flexx.readthedocs.io
  dev_url: http://github.com/zoofIO/flexx
  summary: Python UI tookit based on web technology
  license: BSD 2-Clause

extra:
  recipe-maintainers:
    - almarklein
    - ivoflipse
    - korijn 
