{% set version = "0.4.1" %}

package:
  name: flexx
  version: {{ version }}

source:
  fn: flexx-b2d766117d13f3afd6cc5ace26c4380fd3be6805.tar.gz
  url: https://github.com/zoofIO/flexx/archive/b2d766117d13f3afd6cc5ace26c4380fd3be6805.tar.gz
  sha256: 6815151640a58b60a458c354ce81cfb1315319ae5810160d4c04d86797d94cca

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  number: 0

requirements:
  build:
    - python
    - setuptools
    - tornado
  run:
    - python
    - tornado

test:
  imports:
    - flexx.ui
    - flexx.app
    - flexx.event
    - flexx.pyscript
    - flexx.webruntime
    - flexx.util

about:
  home: http://github.com/zoofIO/flexx
  doc_url: http://flexx.readthedocs.io
  dev_url: http://github.com/zoofIO/flexx
  summary: Python UI tookit based on web technology
  license: BSD 2-Clause

extra:
  recipe-maintainers:
    - almarklein
    - ivoflipse
    - korijn 
