travis:
  secure:
    BINSTAR_TOKEN: D7WAztAhVwVMkw+S9grLliCdOAWO2iTW62DeiYEZ6m/zhXXNUZJy5KCxzkv+wAe6L7RziKVD7C5iyiIR7EUTkHdNsgb+Dr8juXyvKYzQEStwqaa5Waz00WSkGMKmtXhajoXsIWtTdp2YbQ1NOHz27JN1VUfkM3Zvzn367iFbv/tKd83hBmOAvHYA5+ZQlolT6xwlooM/wNkzDgqdZXQGki492MYMRtJgDfDflUa1jLS4HOlSoabbltZjasEJdnYpHvugNhCyuOowjEI7OO/YS1OFehINiIN+KgAyNCtiUlkYL84yrs+CIW1ESKRTAVNq+msYT/XvmMZsRbQ9R155pM7jS08YkJoXqbPCN61i1SZtkjV9Qg82ZFKiab9Jsau93tV6uJ8DU0Q2EZXtvcTK70+UQS3fTczIwxdvMOePwRZs307McaHXXNURgEP9FXqrNExj47Is/BzotGgKPaoaT1cRzGcIxUyV2uRkVvhwXV9QpiciD3w9GUExA/vthE5xYnW9lN4rc1vrtOGhyG1S5h1J63/svG0efuWf4+2YUJ8MZPAcD6aPMNe0qsIq+r2cxSoowIlbGQOnqW7/q9m1LYne3McKx0w85gqlKu+geFzV+5p9hYbxQHgpvny3VBB5POj0VSqUwiRkF/fdTBd7DVjPbb68a/ammZGHs5nPgFs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
