travis:
  secure:
    BINSTAR_TOKEN: BWDt9K3nNbzsS9BWN8HvE001iI5lwINinEzFuAmGURf4R3HtxvISmak2t33xiGUmT5Is4dEDF+tlA23UFYAxsWcFL85sZ/88xHCi3ww5YPjW67HnwFUmnqNz4fx05OrzLDTboQLEJAVzqnFCk/XI8CUFx13WNv2ZWi1mqoTJHc+vZkca/dyrxxJFMxXVHRgy9kNgeAj75/+Iy2QWR5VMAsMbBz9DVP3HALBWknbB7vNDldVWhc1sYSt+IwluNw2H0mauLGeUGTxMqV+eHN/D4XavsTg/Hu69JuMTc5oDZxchPJ+aQRheaShrFjbjLB8zMPgEWGVBF/1XLkuumbfKT4eAlwFrJO/DlQl/MIn3Ex6CmFwWL5peRyeksEt/D7XCcI2WAxJyy+V6IzCawpa1Dda8JIg+f7p/4LAmxHdRRc/WYb9mnZO8SVAkjeStzJNthlXL8KcW5ncnEdyOVfdxzckGo4pleCLCyu0qVMq7dZnPBxAvNMYQDI3cWbj4Rgu0mOEOj2bC1wU6+pFuhRXakCVjrqW66XwKRtvjtPqSbwZ0+jgLyXuboJCV5keMrxCISKLIrVNcLQ07ccZGWdaFbye8E9HczlAajYTMGDA5O2kLKY3jKazToqyw4RmCfubecu/dFGTD6mjRPktOucli6AddMlq/JCKlnx05ope4jt0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
